POST http://localhost:8080/update
Content-Type: application/json

{
  "id": 2,
  "firstName": "BBB",
  "lastName": "AAA",
  "age": 28
}

###

POST http://localhost:8080/register
Content-Type: application/json

{
  "firstName": "awerwr",
  "lastName": "Rojanap",
  "age": 28
}

###
